apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: app1 
  labels: 
    app: app1
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: app1  
  template: 
    metadata: 
      labels: 
        app: app1    
    spec: 
      containers: 
      - name: nginx 
        image: akarapunikhilchandra/app1:v1 
        ports: 
        - containerPort: 80 
---
apiVersion: v1
kind: Service 
metadata: 
  name: app1 
spec: 
  selector: 
    app: app1 
  ports: 
  - name: name-of-service-port 
    protocol: TCP 
    port: 80
    targetPort: 80